services:
  medremindr-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=main
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - PGSSLROOTCERT=${PGSSLROOTCERT}
      - MED_REMINDER_JWT_KEY=${MED_REMINDER_JWT_KEY}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_BUNDLE_ID=${APPLE_BUNDLE_ID}
      - APPLE_PRIVATE_KEY_PATH=${APPLE_PRIVATE_KEY_PATH}
      - YC_S3_KEY_ID=${YC_S3_KEY_ID}
      - YC_S3_SECRET_KEY=${YC_S3_SECRET_KEY}
      - YC_S3_BUCKET=${YC_S3_BUCKET}
      - YC_S3_REGION=${YC_S3_REGION}
      - YC_S3_PRIVATE_ENDPOINT=${YC_S3_PRIVATE_ENDPOINT}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - /Users/azeezabiola/.cloud-certs/root.crt:/Users/azeezabiola/.cloud-certs/root.crt:ro
      - /Users/azeezabiola/AuthKey_236N7KRQ35.p8:/Users/azeezabiola/AuthKey_236N7KRQ35.p8:ro