spring.application.name=MedReminder-server
spring.profiles.active=prod,dev
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#Database Setting
spring.datasource.tomcat.max-wait=10000
jwt.refresh-expiry-days=3650