#Main application settings
spring.application.name=MedReminder-Server
spring.profiles.active=main
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#Transaction DEBUG:
logging.level.org.springframework.transaction.interceptor=DEBUG
logging.level.org.springframework.aop=DEBUG

#Server Settings
server.servlet.context-path=/api/v1

#Database Setting
spring.datasource.tomcat.max-wait=10000

#JWT token refresh expire
jwt.refresh-expiry-days=3650

#Batch Jobs Setting
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

#Batch Jobs Quartz Settings
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=MedReminderScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.threadPool.threadCount=3

#Mailer Settings
spring.mail.host=${MAIL_HOST}
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

#Email Template Settings
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl

#Observability and Metrics Settings
management.endpoints.web.exposure.include=health,info,prometheus,quartz
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application= ${spring.application.name}