jakarta.persistence.database-product-name=PostgreSQL
org.jboss.logging.provider=slf4j
org.hibernate.orm.deprecation=ERROR
org.hibernate.SQL=WARN
logging.level.org.hibernate.tool.schema=WARN
org.hibernate.tool.schema=WARN
